version: '3.7'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'bot_db'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'spring-password'
      MYSQL_ROOT_PASSWORD: 'root-password'
    ports:
      - '5432:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - backend
  kairos-bot:
    image: hirotaka00/kairos-bot:latest
    depends_on:
      - db
    networks:
      - backend
networks:
  backend: